project_id = "fnmkczsvwpzpxyklztkt"

[functions.send-invitation-email]
verify_jwt = false

[functions.form-api]
verify_jwt = false

[functions.send-mfa-code]
verify_jwt = false

[functions.verify-mfa-code]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.execute-data-feed]
verify_jwt = false

[functions.run-scheduled-data-feeds]
verify_jwt = false

[functions.discover-external-fields]
verify_jwt = false

[functions.ldap-test-connection]
verify_jwt = false

[functions.ldap-authenticate]
verify_jwt = false
