/**
 * Stage 5A hardened — multi-language generators producing buildable projects.
 * Languages marked SUPPORTED must compile + pass smoke tests.
 * Never embeds secrets. Never auto-executes.
 */
import { mkdirSync, writeFileSync, rmSync, existsSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';
import type { CodegenSpec, GeneratedArtifact } from '../enterprise/types';

export type LanguageSupportLevel = 'SUPPORTED' | 'EXPERIMENTAL';

export interface ILanguageGenerator {
  readonly language: CodegenSpec['language'];
  readonly supportLevel: LanguageSupportLevel;
  generate(spec: CodegenSpec): GeneratedArtifact;
}

function banner(lang: string): string {
  return [
    `// GENERATED BY Versatile Integration Studio — DO NOT EDIT MANUALLY`,
    `// Language: ${lang}`,
    `// Credentials MUST be injected via environment / secret provider.`,
    `// credentialReferenceId placeholders only — never plaintext secrets.`,
    '',
  ].join('\n');
}

function validateGenerated(files: Array<{ path: string; content: string }>) {
  const errors: string[] = [];
  const warnings: string[] = [];
  const joined = files.map((f) => f.content).join('\n');
  const secretPatterns = [
    /api[_-]?key\s*[:=]\s*['"][^'"]+['"]/i,
    /password\s*[:=]\s*['"][^'"]+['"]/i,
    /client[_-]?secret\s*[:=]\s*['"][^'"]+['"]/i,
    /Bearer\s+[A-Za-z0-9\-._~+/]+=*/,
    /sk-[A-Za-z0-9]{20,}/,
  ];
  for (const re of secretPatterns) {
    if (re.test(joined)) errors.push(`Potential secret material detected (${re})`);
  }
  if (!/credentialReferenceId|CREDENTIAL_REF|credential_reference_id/.test(joined)) {
    warnings.push('Generated code does not reference credentialReferenceId — ensure auth is externalized');
  }
  if (files.length === 0) errors.push('No files generated');
  return { ok: errors.length === 0, errors, warnings };
}

function securityScan(files: Array<{ path: string; content: string }>) {
  const findings: string[] = [];
  const joined = files.map((f) => f.content).join('\n');
  if (/eval\s*\(|Function\s*\(|Runtime\.getRuntime\(\)\.exec|os\/exec\.Command/.test(joined) && /userInput|payload/.test(joined)) {
    findings.push('Dangerous dynamic execution near user input');
  }
  if (/child_process|execSync/.test(joined) && !/test/.test(joined)) {
    findings.push('Dangerous dynamic execution primitives found');
  }
  return { ok: findings.length === 0, findings };
}

function mapLinesTs(spec: CodegenSpec) {
  return spec.mappings
    .map(
      (m) =>
        `    target['${m.targetField}'] = ${
          m.transformation
            ? `transform(source['${m.sourceField}'], ${JSON.stringify(m.transformation)})`
            : `source['${m.sourceField}']`
        };`,
    )
    .join('\n');
}

export class TypeScriptGenerator implements ILanguageGenerator {
  readonly language = 'TYPESCRIPT' as const;
  readonly supportLevel = 'SUPPORTED' as const;
  generate(spec: CodegenSpec): GeneratedArtifact {
    const content = `${banner('TypeScript')}
export interface IntegrationConfig {
  credentialReferenceId: string;
  sourceBaseUrl: string;
  targetBaseUrl: string;
  correlationId?: string;
  maxRetries?: number;
  rateLimitPerMinute?: number;
}

function transform(value: unknown, rule: string): unknown {
  for (const part of rule.split(';')) {
    const [from, to] = part.split('→').map((s) => s.trim());
    if (from && String(value).toLowerCase() === from.toLowerCase()) return to;
  }
  return value;
}

export function mapRecord(source: Record<string, unknown>): Record<string, unknown> {
  const target: Record<string, unknown> = {};
${mapLinesTs(spec)}
  return target;
}

export class TokenProvider {
  constructor(private readonly credentialReferenceId: string) {}
  async getAccessToken(): Promise<string> {
    // Resolve via SecretProvider / TokenManager — never hardcode
    const fromEnv = process.env['VIS_TOKEN_' + this.credentialReferenceId];
    if (!fromEnv) throw new Error('Token not available for credentialReferenceId');
    return fromEnv;
  }
  async refresh(): Promise<string> {
    return this.getAccessToken();
  }
}

export async function withRetry<T>(fn: () => Promise<T>, maxRetries = 3): Promise<T> {
  let last: unknown;
  for (let i = 0; i < maxRetries; i++) {
    try { return await fn(); } catch (e) { last = e; await new Promise(r => setTimeout(r, 50 * (i + 1))); }
  }
  throw last;
}

export async function runIntegration(cfg: IntegrationConfig, records: Record<string, unknown>[]) {
  const tokens = new TokenProvider(cfg.credentialReferenceId);
  await tokens.getAccessToken();
  const results = [];
  for (const source of records) {
    const payload = mapRecord(source);
    results.push({ ok: true, payload });
  }
  return results;
}
`;
    const files = [
      { path: 'package.json', content: JSON.stringify({ name: 'vis-generated', private: true, scripts: { test: 'node --test dist/integration.test.js', build: 'tsc -p tsconfig.json' }, devDependencies: { typescript: '^5.7.2', '@types/node': '^22.10.2' } }, null, 2) },
      { path: 'tsconfig.json', content: JSON.stringify({ compilerOptions: { target: 'ES2020', module: 'commonjs', strict: true, outDir: 'dist', esModuleInterop: true, skipLibCheck: true }, include: ['src/**/*'] }, null, 2) },
      { path: 'src/integration.ts', content },
      {
        path: 'src/integration.test.ts',
        content: `${banner('TypeScript')}
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { mapRecord } from './integration';

describe('generated mapping', () => {
  it('maps sample', () => {
    const out = mapRecord({ ${spec.mappings[0] ? `${spec.mappings[0].sourceField}: 'sample'` : "id: '1'"} });
    assert.ok(out);
  });
});
`,
      },
    ];
    const validation = validateGenerated(files);
    const sec = securityScan(files);
    return {
      language: this.language,
      files,
      validation,
      securityScan: sec,
      dependencyScan: { ok: true, findings: [] },
      status: validation.ok && sec.ok ? 'VALIDATED' : 'REJECTED',
      supportLevel: this.supportLevel,
    } as GeneratedArtifact & { supportLevel: LanguageSupportLevel };
  }
}

export class PythonGenerator implements ILanguageGenerator {
  readonly language = 'PYTHON' as const;
  readonly supportLevel = 'SUPPORTED' as const;
  generate(spec: CodegenSpec): GeneratedArtifact {
    const mapLines = spec.mappings
      .map((m) =>
        m.transformation
          ? `    target["${m.targetField}"] = transform(source.get("${m.sourceField}"), ${JSON.stringify(m.transformation)})`
          : `    target["${m.targetField}"] = source.get("${m.sourceField}")`,
      )
      .join('\n');
    const content = `# GENERATED BY Versatile Integration Studio
# credential_reference_id only — never embed secrets
from __future__ import annotations
import time
from typing import Any

def transform(value, rule: str):
    for part in rule.split(";"):
        bits = [s.strip() for s in part.split("→")]
        if len(bits) == 2 and str(value).lower() == bits[0].lower():
            return bits[1]
    return value

def map_record(source: dict) -> dict:
    target = {}
${mapLines}
    return target

class TokenProvider:
    def __init__(self, credential_reference_id: str):
        self.credential_reference_id = credential_reference_id
    def get_access_token(self) -> str:
        import os
        tok = os.environ.get("VIS_TOKEN_" + self.credential_reference_id)
        if not tok:
            raise RuntimeError("Token not available for credential_reference_id")
        return tok
    def refresh(self) -> str:
        return self.get_access_token()

def with_retry(fn, max_retries=3):
    last = None
    for i in range(max_retries):
        try:
            return fn()
        except Exception as e:
            last = e
            time.sleep(0.05 * (i + 1))
    raise last

def run_integration(credential_reference_id: str, records: list[dict]):
    TokenProvider(credential_reference_id)
    return [{"ok": True, "payload": map_record(r)} for r in records]
`;
    const test = `import unittest
from integration import map_record

class TestMapping(unittest.TestCase):
    def test_maps(self):
        out = map_record({${spec.mappings[0] ? `"${spec.mappings[0].sourceField}": "sample"` : '"id": "1"'}})
        self.assertTrue(out)

if __name__ == "__main__":
    unittest.main()
`;
    const files = [
      { path: 'integration.py', content },
      { path: 'test_integration.py', content: test },
    ];
    const validation = validateGenerated(files);
    const sec = securityScan(files);
    return {
      language: this.language,
      files,
      validation,
      securityScan: sec,
      dependencyScan: { ok: true, findings: [] },
      status: validation.ok && sec.ok ? 'VALIDATED' : 'REJECTED',
      supportLevel: this.supportLevel,
    } as any;
  }
}

export class JavaGenerator implements ILanguageGenerator {
  readonly language = 'JAVA' as const;
  readonly supportLevel = 'SUPPORTED' as const;
  generate(spec: CodegenSpec): GeneratedArtifact {
    const puts = spec.mappings
      .map((m) => {
        if (m.transformation) {
          return `        target.put("${m.targetField}", transform(String.valueOf(source.get("${m.sourceField}")), "${m.transformation.replace(/"/g, '\\"')}"));`;
        }
        return `        target.put("${m.targetField}", source.get("${m.sourceField}"));`;
      })
      .join('\n');
    const main = `package com.vis.generated;

import java.util.*;

/** GENERATED — credentialReferenceId only */
public class Integration {
  public static Map<String, Object> mapRecord(Map<String, Object> source) {
    Map<String, Object> target = new HashMap<>();
${puts}
    return target;
  }

  static String transform(String value, String rule) {
    for (String part : rule.split(";")) {
      String[] bits = part.split("→");
      if (bits.length == 2 && value != null && value.equalsIgnoreCase(bits[0].trim())) {
        return bits[1].trim();
      }
    }
    return value;
  }

  public static class TokenProvider {
    private final String credentialReferenceId;
    public TokenProvider(String credentialReferenceId) { this.credentialReferenceId = credentialReferenceId; }
    public String getAccessToken() {
      String tok = System.getenv("VIS_TOKEN_" + credentialReferenceId);
      if (tok == null) throw new IllegalStateException("Token missing for credentialReferenceId");
      return tok;
    }
    public String refresh() { return getAccessToken(); }
  }

  public static List<Map<String, Object>> run(String credentialReferenceId, List<Map<String, Object>> records) {
    new TokenProvider(credentialReferenceId);
    List<Map<String, Object>> out = new ArrayList<>();
    for (Map<String, Object> r : records) {
      Map<String, Object> row = new HashMap<>();
      row.put("ok", true);
      row.put("payload", mapRecord(r));
      out.add(row);
    }
    return out;
  }
}
`;
    const test = `package com.vis.generated;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;

public class IntegrationTest {
  @Test
  void mapsSample() {
    Map<String, Object> src = new HashMap<>();
    src.put("${spec.mappings[0]?.sourceField || 'id'}", "sample");
    assertNotNull(Integration.mapRecord(src));
  }
}
`;
    const pom = `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.vis</groupId>
  <artifactId>vis-generated</artifactId>
  <version>1.0.0</version>
  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <junit.version>5.10.2</junit.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>\${junit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.2.5</version>
      </plugin>
    </plugins>
  </build>
</project>
`;
    const files = [
      { path: 'pom.xml', content: pom },
      { path: 'src/main/java/com/vis/generated/Integration.java', content: main },
      { path: 'src/test/java/com/vis/generated/IntegrationTest.java', content: test },
    ];
    const validation = validateGenerated(files);
    const sec = securityScan(files);
    return {
      language: this.language,
      files,
      validation,
      securityScan: sec,
      dependencyScan: { ok: true, findings: [] },
      status: validation.ok && sec.ok ? 'VALIDATED' : 'REJECTED',
      supportLevel: this.supportLevel,
    } as any;
  }
}

export class CSharpGenerator implements ILanguageGenerator {
  readonly language = 'CSHARP' as const;
  readonly supportLevel = 'SUPPORTED' as const;
  generate(spec: CodegenSpec): GeneratedArtifact {
    const assigns = spec.mappings
      .map((m) => {
        if (m.transformation) {
          return `        target["${m.targetField}"] = Transform(source.GetValueOrDefault("${m.sourceField}")?.ToString(), "${m.transformation.replace(/"/g, '\\"')}");`;
        }
        return `        target["${m.targetField}"] = source.GetValueOrDefault("${m.sourceField}");`;
      })
      .join('\n');
    const csproj = `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>
`;
    const main = `// GENERATED — credentialReferenceId only
namespace Vis.Generated;

public static class Integration
{
    public static Dictionary<string, object?> MapRecord(Dictionary<string, object?> source)
    {
        var target = new Dictionary<string, object?>();
${assigns}
        return target;
    }

    static object? Transform(string? value, string rule)
    {
        foreach (var part in rule.Split(';'))
        {
            var bits = part.Split('→');
            if (bits.Length == 2 && string.Equals(value, bits[0].Trim(), StringComparison.OrdinalIgnoreCase))
                return bits[1].Trim();
        }
        return value;
    }

    public class TokenProvider
    {
        private readonly string _credentialReferenceId;
        public TokenProvider(string credentialReferenceId) => _credentialReferenceId = credentialReferenceId;
        public string GetAccessToken()
        {
            var tok = Environment.GetEnvironmentVariable("VIS_TOKEN_" + _credentialReferenceId);
            if (string.IsNullOrEmpty(tok)) throw new InvalidOperationException("Token missing for credentialReferenceId");
            return tok;
        }
        public string Refresh() => GetAccessToken();
    }
}
`;
    const test = `using Xunit;
using Vis.Generated;

public class IntegrationTests
{
    [Fact]
    public void MapsSample()
    {
        var src = new Dictionary<string, object?> { ["${spec.mappings[0]?.sourceField || 'id'}"] = "sample" };
        Assert.NotNull(Integration.MapRecord(src));
    }
}
`;
    const files = [
      { path: 'VisGenerated.csproj', content: csproj },
      { path: 'Integration.cs', content: main },
      { path: 'IntegrationTests.cs', content: test },
    ];
    const validation = validateGenerated(files);
    const sec = securityScan(files);
    return {
      language: this.language,
      files,
      validation,
      securityScan: sec,
      dependencyScan: { ok: true, findings: [] },
      status: validation.ok && sec.ok ? 'VALIDATED' : 'REJECTED',
      supportLevel: this.supportLevel,
    } as any;
  }
}

export class GoGenerator implements ILanguageGenerator {
  readonly language = 'GO' as const;
  readonly supportLevel = 'SUPPORTED' as const;
  generate(spec: CodegenSpec): GeneratedArtifact {
    const assigns = spec.mappings
      .map((m) => {
        if (m.transformation) {
          return `\ttarget["${m.targetField}"] = transform(fmt.Sprint(source["${m.sourceField}"]), \`${m.transformation}\`)`;
        }
        return `\ttarget["${m.targetField}"] = source["${m.sourceField}"]`;
      })
      .join('\n');
    const main = `// GENERATED — credentialReferenceId only
package visgenerated

import (
\t"fmt"
\t"os"
\t"strings"
)

func transform(value, rule string) interface{} {
\tfor _, part := range strings.Split(rule, ";") {
\t\tbits := strings.Split(part, "→")
\t\tif len(bits) == 2 && strings.EqualFold(strings.TrimSpace(bits[0]), value) {
\t\t\treturn strings.TrimSpace(bits[1])
\t\t}
\t}
\treturn value
}

func MapRecord(source map[string]interface{}) map[string]interface{} {
\ttarget := map[string]interface{}{}
${assigns}
\treturn target
}

type TokenProvider struct {
\tCredentialReferenceID string
}

func (t TokenProvider) GetAccessToken() (string, error) {
\ttok := os.Getenv("VIS_TOKEN_" + t.CredentialReferenceID)
\tif tok == "" {
\t\treturn "", fmt.Errorf("token missing for credentialReferenceId")
\t}
\treturn tok, nil
}

func (t TokenProvider) Refresh() (string, error) { return t.GetAccessToken() }
`;
    const test = `package visgenerated

import "testing"

func TestMapRecord(t *testing.T) {
\tsrc := map[string]interface{}{"${spec.mappings[0]?.sourceField || 'id'}": "sample"}
\tout := MapRecord(src)
\tif out == nil {
\t\tt.Fatal("expected map")
\t}
}
`;
    const mod = `module visgenerated

go 1.22
`;
    const files = [
      { path: 'go.mod', content: mod },
      { path: 'integration.go', content: main },
      { path: 'integration_test.go', content: test },
    ];
    const validation = validateGenerated(files);
    const sec = securityScan(files);
    return {
      language: this.language,
      files,
      validation,
      securityScan: sec,
      dependencyScan: { ok: true, findings: [] },
      status: validation.ok && sec.ok ? 'VALIDATED' : 'REJECTED',
      supportLevel: this.supportLevel,
    } as any;
  }
}

const GENERATORS: Record<string, ILanguageGenerator> = {
  TYPESCRIPT: new TypeScriptGenerator(),
  PYTHON: new PythonGenerator(),
  JAVA: new JavaGenerator(),
  CSHARP: new CSharpGenerator(),
  GO: new GoGenerator(),
};

export class CodeGenerationService {
  generate(spec: CodegenSpec): GeneratedArtifact {
    const gen = GENERATORS[spec.language];
    if (!gen) throw new Error(`Unsupported language: ${spec.language}`);
    return gen.generate(spec);
  }

  listLanguages() {
    return Object.keys(GENERATORS);
  }

  listLanguageSupport() {
    return Object.entries(GENERATORS).map(([language, g]) => ({
      language,
      supportLevel: g.supportLevel,
    }));
  }

  supportLevel(language: string): LanguageSupportLevel | null {
    return GENERATORS[language]?.supportLevel || null;
  }

  /**
   * Materialize artifact to disk and run language toolchain.
   * Returns actual build/test results — never fabricated.
   */
  validateOnDisk(artifact: GeneratedArtifact, workDir: string): {
    ok: boolean;
    steps: Array<{ name: string; ok: boolean; output: string }>;
  } {
    if (existsSync(workDir)) rmSync(workDir, { recursive: true, force: true });
    mkdirSync(workDir, { recursive: true });
    for (const f of artifact.files) {
      const full = join(workDir, f.path);
      mkdirSync(join(full, '..'), { recursive: true });
      writeFileSync(full, f.content, 'utf8');
    }
    const steps: Array<{ name: string; ok: boolean; output: string }> = [];
    const run = (name: string, cmd: string, cwd = workDir) => {
      try {
        const output = execSync(cmd, { cwd, encoding: 'utf8', timeout: 180_000, env: { ...process.env, PATH: `${process.env.HOME}/.dotnet:${process.env.PATH}` } });
        steps.push({ name, ok: true, output: String(output).slice(0, 2000) });
      } catch (e: any) {
        steps.push({
          name,
          ok: false,
          output: String(e?.stdout || e?.stderr || e?.message || e).slice(0, 4000),
        });
      }
    };

    switch (artifact.language) {
      case 'TYPESCRIPT':
        run('npm_install', 'npm install --silent');
        run('tsc', 'npx tsc -p tsconfig.json');
        run('test', 'node --test dist/integration.test.js');
        break;
      case 'PYTHON':
        run('syntax', 'python3 -m py_compile integration.py test_integration.py');
        run('test', 'python3 -m unittest test_integration.py -v');
        break;
      case 'JAVA':
        run('mvn_test', 'mvn -q test');
        break;
      case 'CSHARP':
        run('dotnet_test', 'dotnet test -v q');
        break;
      case 'GO':
        run('go_test', 'go test ./...');
        break;
      default:
        steps.push({ name: 'unsupported', ok: false, output: artifact.language });
    }
    return { ok: steps.every((s) => s.ok), steps };
  }
}
