/**
 * Stage 5A — AI code generation from approved ExecutionPlan / design.
 * Never embeds secrets. Never auto-executes. Requires validation + approval.
 */
import type { CodegenSpec, GeneratedArtifact } from '../enterprise/types';

export interface ILanguageGenerator {
  readonly language: CodegenSpec['language'];
  generate(spec: CodegenSpec): GeneratedArtifact;
}

function banner(lang: string): string {
  return [
    `// GENERATED BY Versatile Integration Studio — DO NOT EDIT MANUALLY`,
    `// Language: ${lang}`,
    `// Credentials MUST be injected via environment / secret provider.`,
    `// credentialReferenceId placeholders only — never plaintext secrets.`,
    '',
  ].join('\n');
}

function validateGenerated(files: Array<{ path: string; content: string }>): {
  ok: boolean;
  errors: string[];
  warnings: string[];
} {
  const errors: string[] = [];
  const warnings: string[] = [];
  const joined = files.map((f) => f.content).join('\n');
  const secretPatterns = [
    /api[_-]?key\s*[:=]\s*['"][^'"]+['"]/i,
    /password\s*[:=]\s*['"][^'"]+['"]/i,
    /client[_-]?secret\s*[:=]\s*['"][^'"]+['"]/i,
    /Bearer\s+[A-Za-z0-9\-._~+/]+=*/,
    /sk-[A-Za-z0-9]{20,}/,
  ];
  for (const re of secretPatterns) {
    if (re.test(joined)) errors.push(`Potential secret material detected (${re})`);
  }
  if (!joined.includes('credentialReferenceId') && !joined.includes('CREDENTIAL_REF')) {
    warnings.push('Generated code does not reference credentialReferenceId — ensure auth is externalized');
  }
  if (files.length === 0) errors.push('No files generated');
  return { ok: errors.length === 0, errors, warnings };
}

function securityScan(files: Array<{ path: string; content: string }>) {
  const findings: string[] = [];
  const joined = files.map((f) => f.content).join('\n');
  if (/eval\s*\(|Function\s*\(|child_process|execSync/.test(joined)) {
    findings.push('Dangerous dynamic execution primitives found');
  }
  if (/process\.env\.[A-Z0-9_]*SECRET|process\.env\.[A-Z0-9_]*PASSWORD/.test(joined)) {
    // ok — env refs are allowed; plaintext assignment is not
  }
  return { ok: findings.length === 0, findings };
}

function dependencyScan(language: string) {
  // Stub — real SCA would run in CI
  return { ok: true, findings: [] as string[], note: `${language} dependency scan deferred to CI` };
}

export class TypeScriptGenerator implements ILanguageGenerator {
  readonly language = 'TYPESCRIPT' as const;
  generate(spec: CodegenSpec): GeneratedArtifact {
    const mapLines = spec.mappings
      .map(
        (m) =>
          `    target['${m.targetField}'] = ${
            m.transformation
              ? `transform(source['${m.sourceField}'], ${JSON.stringify(m.transformation)})`
              : `source['${m.sourceField}']`
          };`,
      )
      .join('\n');
    const content = `${banner('TypeScript')}
export interface IntegrationConfig {
  credentialReferenceId: string; // NEVER embed secrets
  sourceBaseUrl: string;
  targetBaseUrl: string;
  correlationId?: string;
}

function transform(value: unknown, rule: string): unknown {
  for (const part of rule.split(';')) {
    const [from, to] = part.split('→').map((s) => s.trim());
    if (from && String(value).toLowerCase() === from.toLowerCase()) return to;
  }
  return value;
}

export function mapRecord(source: Record<string, unknown>): Record<string, unknown> {
  const target: Record<string, unknown> = {};
${mapLines}
  return target;
}

export async function runIntegration(cfg: IntegrationConfig, records: Record<string, unknown>[]) {
  // Auth via credentialReferenceId resolved by TokenManager / SecretProvider at runtime
  const results = [];
  for (const source of records) {
    const payload = mapRecord(source);
    // Idempotent upsert using matching fields: ${spec.matchingStrategy.targetFields.join(', ')}
    results.push({ ok: true, payload });
  }
  return results;
}

// Integration: ${spec.integrationId} version: ${spec.versionId}
// Summary: ${spec.designSummary.replace(/\n/g, ' ')}
`;
    const files = [
      { path: 'src/integration.ts', content },
      {
        path: 'src/integration.test.ts',
        content: `${banner('TypeScript')}
import { mapRecord } from './integration';
describe('generated mapping', () => {
  it('maps sample', () => {
    const out = mapRecord({ ${spec.mappings[0] ? `${spec.mappings[0].sourceField}: 'sample'` : "id: '1'"} });
    expect(out).toBeTruthy();
  });
});
`,
      },
    ];
    const validation = validateGenerated(files);
    const sec = securityScan(files);
    return {
      language: this.language,
      files,
      validation,
      securityScan: sec,
      dependencyScan: dependencyScan(this.language),
      status: validation.ok && sec.ok ? 'VALIDATED' : 'REJECTED',
    };
  }
}

export class PythonGenerator implements ILanguageGenerator {
  readonly language = 'PYTHON' as const;
  generate(spec: CodegenSpec): GeneratedArtifact {
    const mapLines = spec.mappings
      .map((m) =>
        m.transformation
          ? `    target["${m.targetField}"] = transform(source.get("${m.sourceField}"), ${JSON.stringify(m.transformation)})`
          : `    target["${m.targetField}"] = source.get("${m.sourceField}")`,
      )
      .join('\n');
    const content = `# GENERATED BY Versatile Integration Studio
# credential_reference_id only — never embed secrets

def transform(value, rule: str):
    for part in rule.split(";"):
        bits = [s.strip() for s in part.split("→")]
        if len(bits) == 2 and str(value).lower() == bits[0].lower():
            return bits[1]
    return value

def map_record(source: dict) -> dict:
    target = {}
${mapLines}
    return target

def run_integration(credential_reference_id: str, records: list[dict]):
    # Resolve secrets via SecretProvider using credential_reference_id
    return [{"ok": True, "payload": map_record(r)} for r in records]
`;
    const files = [{ path: 'integration.py', content }];
    const validation = validateGenerated(files);
    const sec = securityScan(files);
    return {
      language: this.language,
      files,
      validation,
      securityScan: sec,
      dependencyScan: dependencyScan(this.language),
      status: validation.ok && sec.ok ? 'VALIDATED' : 'REJECTED',
    };
  }
}

/** Stub generators for Java / C# / Go — same contract, minimal scaffolding. */
function stubGenerator(language: CodegenSpec['language'], ext: string, comment: string): ILanguageGenerator {
  return {
    language,
    generate(spec: CodegenSpec): GeneratedArtifact {
      const content = `${comment} GENERATED — credentialReferenceId only\n// integration=${spec.integrationId}\n// Implement using platform SDK\n`;
      const files = [{ path: `Integration.${ext}`, content }];
      const validation = validateGenerated(files);
      return {
        language,
        files,
        validation,
        securityScan: securityScan(files),
        dependencyScan: dependencyScan(language),
        status: validation.ok ? 'VALIDATED' : 'REJECTED',
      };
    },
  };
}

const GENERATORS: Record<string, ILanguageGenerator> = {
  TYPESCRIPT: new TypeScriptGenerator(),
  PYTHON: new PythonGenerator(),
  JAVA: stubGenerator('JAVA', 'java', '//'),
  CSHARP: stubGenerator('CSHARP', 'cs', '//'),
  GO: stubGenerator('GO', 'go', '//'),
};

export class CodeGenerationService {
  generate(spec: CodegenSpec): GeneratedArtifact {
    const gen = GENERATORS[spec.language];
    if (!gen) throw new Error(`Unsupported language: ${spec.language}`);
    return gen.generate(spec);
  }

  listLanguages() {
    return Object.keys(GENERATORS);
  }
}
