
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';
import { WorkflowExecutionService } from '@/services/workflowExecution';
import { FormRuleWorkflowTrigger } from '@/services/formRuleWorkflowTrigger';
import { useAuth } from '@/contexts/AuthContext';
import { Form } from '@/types/form';

export function useFormSubmissionHandler(formId: string | undefined, form?: Form) {
  const { userProfile } = useAuth();

  const assignRolesToUsers = async (formData: Record<string, any>) => {
    if (!form?.fields) return;

    // Find user picker fields with role assignment configuration
    const userPickerFields = form.fields.filter(
      field => field.type === 'user-picker' && field.customConfig?.assignRole
    );

    for (const field of userPickerFields) {
      const fieldValue = formData[field.id];
      const assignRoleId = field.customConfig?.assignRole;
      
      if (!fieldValue || !assignRoleId) continue;

      // Fetch the role data from the database
      const { data: roleData, error: roleError } = await supabase
        .from('roles')
        .select('*')
        .eq('id', assignRoleId)
        .single();

      if (roleError || !roleData) {
        console.error(`Role not found for ID: ${assignRoleId}`, roleError);
        continue;
      }

      // Handle both single and multiple user selections
      const userIds = Array.isArray(fieldValue) ? fieldValue : [fieldValue];
      
      for (const userId of userIds) {
        if (!userId) continue;
        
        try {
          console.log(`Assigning role ${roleData.name} (ID: ${roleData.id}) to user ${userId}`);
          
          // Assign role to user using user_role_assignments table
          const { error } = await supabase
            .from('user_role_assignments')
            .upsert({
              user_id: userId,
              role_id: assignRoleId,
              assigned_by: userProfile?.id
            }, {
              onConflict: 'user_id,role_id'
            });

          if (error) {
            console.error(`Error assigning role ${roleData.name} to user ${userId}:`, error);
          } else {
            console.log(`Successfully assigned role ${roleData.name} to user ${userId}`);
          }
        } catch (error) {
          console.error(`Failed to assign role to user ${userId}:`, error);
        }
      }
    }
  };

  // Note: submission_ref_id is auto-generated by database trigger (auto_generate_submission_ref_id)
  // No need to generate it client-side

  const handleFormSubmit = async (formData: Record<string, any>) => {
    try {
      console.log('📝 Submitting form data to database:', formData);
      
      // Save form submission to database - submission_ref_id is auto-generated by DB trigger
      const submissionPayload = {
        form_id: formId,
        submission_data: formData,
        submitted_at: new Date().toISOString(),
        submitted_by: userProfile?.id || null,
      };
      
      const { data: submission, error: submissionError } = await supabase
        .from('form_submissions')
        .insert(submissionPayload)
        .select()
        .single();

      if (submissionError) {
        console.error('❌ Error saving submission:', submissionError);
        throw new Error('Failed to save submission');
      }

      console.log('✅ Form submission saved with ID:', submission.id);
      
      // Run role assignments in background (don't await)
      assignRolesToUsers(formData).catch(err => console.error('Role assignment error:', err));
      
      // Show success toast immediately
      toast({
        title: "Success!",
        description: "Your form has been submitted successfully.",
      });

      // Trigger workflows in background (don't block submission)
      if (formId && userProfile?.id) {
        const enhancedFormData = {
          ...formData,
          userEmail: userProfile.email || formData.email,
          submittedBy: userProfile.id,
          submitterName: `${userProfile.first_name || ''} ${userProfile.last_name || ''}`.trim(),
          submissionRefId: submission.submission_ref_id
        };
        
        // Run workflow triggers in background
        Promise.all([
          WorkflowExecutionService.triggerWorkflowsForFormSubmission(
            formId,
            enhancedFormData,
            submission.id,
            userProfile.id
          ),
          FormRuleWorkflowTrigger.evaluateAndTriggerWorkflows(
            formId,
            enhancedFormData,
            submission.id,
            userProfile.id
          )
        ]).catch(err => console.error('Background workflow trigger error:', err));
      }

      // Return submission data including reference ID
      return {
        submissionId: submission.id,
        submissionRefId: submission.submission_ref_id
      };
    } catch (error) {
      console.error('❌ Error submitting form:', error);
      toast({
        title: "Submission Failed",
        description: "There was an error submitting your form. Please try again.",
        variant: "destructive",
      });
      throw error;
    }
  };

  return { handleFormSubmit };
}
